### ISSUE TITLE
Don't use "X-" prefix for the X-NuGet-ApiKey header

### ISSUE THREAD

**Issue by jeffhandley** [MyGet/PackageSourceDiscovery#1]
The use of `X-` as a prefix for HTTP headers has been deprecated.
See: http://www.ietf.org/rfc/rfc6648.txt

We should just `NuGet-ApiKey` instead.  Note that NuGet already uses a `NuGet-Operation` header too.

**Comment by maartenba** [comment]
Fixed in the spec and sample code. The NuGet package will keep using both to ensure backwards compatibility.
