### ISSUE TITLE
Require a title for direct package source links

### ISSUE THREAD

**Issue by jeffhandley** [MyGet/PackageSourceDiscovery#2]
When linking directly to a package source, we should require an `id` attribute on the link tag.  This can provide a unique name for the package source.

The XML+RSD model can provide the additional metadata.  The spec presently states that the XML+ATOM model cannot.  By requiring the `id` attribute, we can at least get the source name, which is very important.  The `id` should be required such that its value can be used for uniqueness.  NuGet doesn't allow 2 package sources by the same name, so if a package source with that name is already registered, the tool should emit a message stating the package source was skipped because it's already registered.

I favor `id` over `title` here because title would be a more freeform value, whereas `id` is generally understood to be a succinct and unique value, not a fully descriptive one.

UPDATE: See comment below - I've changed my position and think title should be used instead of id.

**Comment by jeffhandley** [comment]
On second thought though, the id would generally be the HTML DOM id for the element, and there could be conflicts on this.  And with ASP.NET WebForms, if this was being generated as a server-side tag because it was implemented as a user control, then you wouldn't have as much control over it.

With this, I'm changing my mind and suggest rather that `title` be used instead of `id`.

**Comment by maartenba** [comment]
Changed the spec and updated the PowerShell package. Thanks!
