### ISSUE TITLE
Use a better example for the link URIs

### ISSUE THREAD

**Issue by jeffhandley** [MyGet/PackageSourceDiscovery#3]
Presently, the spec uses http://www.xavierdecoster.com as the link URIs for both the XML+RSD and the ATOM+XML links.  This is confusing and it doesn't truly illustrate the URI values one should use.

I recommend using better examples for those URIs.  For the direct package source URI, you could use the WebMatrix Curated Feed URI: http://nuget.org/api/v2/curated-feeds/WebMatrix/Packages, with the title of "WebMatrix Package Source" on the link.  For the RSD link, you could use the URI that MyGet has for hosting that resource.

**Comment by xavierdecoster** [comment]
Fixed. Thx!
