### ISSUE TITLE
every time I open a project in visual studio a new line is added to Documents\WindowsPowerShell\NuGet_profile.ps1

### ISSUE THREAD

**Issue by ghost** [MyGet/PackageSourceDiscovery#7]
this is now how that file looks on my machine

"Import-Module DiscoverPackageSources -DisableNameChecking
Import-Module DiscoverPackageSources -DisableNameChecking

Import-Module DiscoverPackageSources -DisableNameChecking

Import-Module DiscoverPackageSources -DisableNameChecking

Import-Module DiscoverPackageSources -DisableNameChecking

Import-Module DiscoverPackageSources -DisableNameChecking

Import-Module DiscoverPackageSources -DisableNameChecking"

and powershell is taking longer and longer to start

**Comment by maartenba** [comment]
Fixed, thanks!
